### ISSUE TITLE
compilation warning: NSInteger should not be used as format argument

### ISSUE THREAD

**Issue by mattneub** [kballard/feedparser#19]
[self abortParsing:parser withString:[NSString stringWithFormat:@"Non-UTF8 data found in CDATA block at line %d", [parser lineNumber]]];

in _FPExtensionElementNode.m_. 

> Values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead

Suggested fix:

    [self abortParsing:parser withString:[NSString stringWithFormat:@"Non-UTF8 data found in CDATA block at line %ld", (long)[parser lineNumber]]];

**Comment by kballard** [comment]
Thanks for filing these two issues! I didn't realize anyone was still using this. I've gone ahead and fixed the test suite too.

**Comment by mattneub** [comment]
Thanks!
