### ISSUE TITLE
Warning: NSGregorianCalendar is deprecated

### ISSUE THREAD

**Issue by mattneub** [kballard/feedparser#20]
NSCalendar *calendar = [[[NSCalendar alloc] initWithCalendarIdentifier:NSGregorianCalendar] autorelease];

in _NSDate_FeedParserExtensions.m_.

> 'NSGregorianCalendar' is deprecated: first deprecated in iOS 8.0 - Use NSCalendarIdentifierGregorian instead

Suggested fix:

	NSCalendar *calendar = [[[NSCalendar alloc] initWithCalendarIdentifier:NSCalendarIdentifierGregorian] autorelease];

**Comment by kballard** [comment]
Fixed by 66d797bacf475d9c98ebdcec591048b06a7b18a7.
