### ISSUE TITLE
Adopt NSSecureCoding?

### ISSUE THREAD

**Issue by mattneub** [kballard/feedparser#22]
This is absolutely no big deal and I know you're way busy doing important stuff, but...

My app uses FPFeed's coding support to archive a downloaded feed to Data (NSData). Well, as you are no doubt aware, doing that the old way is deprecated starting in iOS 12; you're supposed to adopt NSSecureCoding. 

I am pretty sure that all this requires is that NSCoding be changed everywhere to NSSecureCoding in the interface files, and that the implementation of each class where we did that should contain this line: `+ (BOOL)supportsSecureCoding { return YES; }`

So it wouldn't be too onerous, I believe.

**Comment by mattneub** [comment]
OK, sorry, this is going to be more work than I thought; I'm having trouble with `extensionElements` and I don't know why.

**Comment by kballard** [comment]
Hi Matt,

I started looking into this myself. It's easy enough to adjust the test to not require secure coding, so you can work around it for now by disabling secure coding. The new test looks like

```objc
- (void)testArchiving {
	// test all fixtures to ensure the unarchived object is equal to the archived one
	NSArray *fixtures = [NSArray arrayWithObjects:@"sample-rss-091.rss", @"sample-rss-092.rss",
						 @"sample-rss-2.rss", @"extensions.rss", @"rss-with-atom.rss", @"google-news.rss", nil];
	for (NSString *fixture in fixtures) {
		FDPFeed *feed = [self feedFromFixture:fixture];
		if (feed == nil) continue;
        NSError *error;
        NSData *data = [NSKeyedArchiver archivedDataWithRootObject:feed requiringSecureCoding:NO error:&error];
        XCTAssertNotNil(data, "error: %@", error);
        NSKeyedUnarchiver *unarchiver = [[NSKeyedUnarchiver alloc] initForReadingFromData:data error:&error];
        XCTAssertNotNil(unarchiver, "error: %@", error);
        unarchiver.requiresSecureCoding = NO;
        FDPFeed *newFeed = [unarchiver decodeObjectForKey:NSKeyedArchiveRootObjectKey];
        XCTAssertNotNil(newFeed, "error: %@", unarchiver.error);
		XCTAssertEqualObjects(feed, newFeed);
	}
}
```

and I will be pushing that fix to the repo soon.

But you're right in that the classes certainly should support secure coding if possible. I will see if it's reasonable to add that support.

**Comment by kballard** [comment]
As best I can tell, the issue with `extensionElements` is if you say `[coder decodeObjectOfClass:[NSArray class] forKey:@"key"]` this works if the array contains primitives like `NSString`, but if the array contains custom classes then you need to use `-decodeObjectOfClasses:forKey:` instead.

I don't get why they didn't just add something like `-decodeArrayOfClass:forKey:`, `-decodeSetOfClass:forKey:`, etc. That approach would work better for Swift too.

**Comment by lilyball** [comment]
Fixed.

**Comment by mattneub** [comment]
Wow, thanks! Seems to be working perfectly. Did I mention wow? And also thanks??
